//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapQuoteAPI {

public class ITapQuoteAPI : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ITapQuoteAPI(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ITapQuoteAPI obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ITapQuoteAPI obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ITapQuoteAPI() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_ITapQuoteAPI(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual int SetAPINotify(ITapQuoteAPINotify apiNotify) {
    int ret = TapQuotePINVOKE.ITapQuoteAPI_SetAPINotify(swigCPtr, ITapQuoteAPINotify.getCPtr(apiNotify));
    return ret;
  }

  public virtual int SetHostAddress(string IP, ushort port) {
    int ret = TapQuotePINVOKE.ITapQuoteAPI_SetHostAddress(swigCPtr, IP, port);
    return ret;
  }

  public virtual int Login(TapAPIQuoteLoginAuth loginAuth) {
    int ret = TapQuotePINVOKE.ITapQuoteAPI_Login(swigCPtr, TapAPIQuoteLoginAuth.getCPtr(loginAuth));
    return ret;
  }

  public virtual int Disconnect() {
    int ret = TapQuotePINVOKE.ITapQuoteAPI_Disconnect(swigCPtr);
    return ret;
  }

  public virtual int QryCommodity(out uint sessionID) {
    int ret = TapQuotePINVOKE.ITapQuoteAPI_QryCommodity(swigCPtr, out sessionID);
    return ret;
  }

  public virtual int QryContract(out uint sessionID, TapAPICommodity qryReq) {
    int ret = TapQuotePINVOKE.ITapQuoteAPI_QryContract(swigCPtr, out sessionID, TapAPICommodity.getCPtr(qryReq));
    return ret;
  }

  public virtual int SubscribeQuote(out uint sessionID, TapAPIContract contract) {
    int ret = TapQuotePINVOKE.ITapQuoteAPI_SubscribeQuote(swigCPtr, out sessionID, TapAPIContract.getCPtr(contract));
    return ret;
  }

  public virtual int UnSubscribeQuote(out uint sessionID, TapAPIContract contract) {
    int ret = TapQuotePINVOKE.ITapQuoteAPI_UnSubscribeQuote(swigCPtr, out sessionID, TapAPIContract.getCPtr(contract));
    return ret;
  }

  public ITapQuoteAPI() : this(TapQuotePINVOKE.new_ITapQuoteAPI(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("SetAPINotify", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateITapQuoteAPI_0(SwigDirectorMethodSetAPINotify);
    if (SwigDerivedClassHasMethod("SetHostAddress", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateITapQuoteAPI_1(SwigDirectorMethodSetHostAddress);
    if (SwigDerivedClassHasMethod("Login", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateITapQuoteAPI_2(SwigDirectorMethodLogin);
    if (SwigDerivedClassHasMethod("Disconnect", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateITapQuoteAPI_3(SwigDirectorMethodDisconnect);
    if (SwigDerivedClassHasMethod("QryCommodity", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateITapQuoteAPI_4(SwigDirectorMethodQryCommodity);
    if (SwigDerivedClassHasMethod("QryContract", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateITapQuoteAPI_5(SwigDirectorMethodQryContract);
    if (SwigDerivedClassHasMethod("SubscribeQuote", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateITapQuoteAPI_6(SwigDirectorMethodSubscribeQuote);
    if (SwigDerivedClassHasMethod("UnSubscribeQuote", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateITapQuoteAPI_7(SwigDirectorMethodUnSubscribeQuote);
    TapQuotePINVOKE.ITapQuoteAPI_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(ITapQuoteAPI))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private int SwigDirectorMethodSetAPINotify(global::System.IntPtr apiNotify) {
    return SetAPINotify((apiNotify == global::System.IntPtr.Zero) ? null : new ITapQuoteAPINotify(apiNotify, false));
  }

  private int SwigDirectorMethodSetHostAddress(string IP, ushort port) {
    return SetHostAddress(IP, port);
  }

  private int SwigDirectorMethodLogin(global::System.IntPtr loginAuth) {
    return Login((loginAuth == global::System.IntPtr.Zero) ? null : new TapAPIQuoteLoginAuth(loginAuth, false));
  }

  private int SwigDirectorMethodDisconnect() {
    return Disconnect();
  }

  private int SwigDirectorMethodQryCommodity(global::System.IntPtr sessionID) {
            uint id = (uint)sessionID;
    return QryCommodity(out id);
  }

  private int SwigDirectorMethodQryContract(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
            uint id = (uint)sessionID;
            return QryContract(out id, (qryReq == global::System.IntPtr.Zero) ? null : new TapAPICommodity(qryReq, false));
  }

  private int SwigDirectorMethodSubscribeQuote(global::System.IntPtr sessionID, global::System.IntPtr contract) {
            uint id = (uint)sessionID;
            return SubscribeQuote(out id, (contract == global::System.IntPtr.Zero) ? null : new TapAPIContract(contract, false));
  }

  private int SwigDirectorMethodUnSubscribeQuote(global::System.IntPtr sessionID, global::System.IntPtr contract) {
            uint id = (uint)sessionID;
            return UnSubscribeQuote(out id, (contract == global::System.IntPtr.Zero) ? null : new TapAPIContract(contract, false));
  }

  public delegate int SwigDelegateITapQuoteAPI_0(global::System.IntPtr apiNotify);
  public delegate int SwigDelegateITapQuoteAPI_1(string IP, ushort port);
  public delegate int SwigDelegateITapQuoteAPI_2(global::System.IntPtr loginAuth);
  public delegate int SwigDelegateITapQuoteAPI_3();
  public delegate int SwigDelegateITapQuoteAPI_4(global::System.IntPtr sessionID);
  public delegate int SwigDelegateITapQuoteAPI_5(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapQuoteAPI_6(global::System.IntPtr sessionID, global::System.IntPtr contract);
  public delegate int SwigDelegateITapQuoteAPI_7(global::System.IntPtr sessionID, global::System.IntPtr contract);

  private SwigDelegateITapQuoteAPI_0 swigDelegate0;
  private SwigDelegateITapQuoteAPI_1 swigDelegate1;
  private SwigDelegateITapQuoteAPI_2 swigDelegate2;
  private SwigDelegateITapQuoteAPI_3 swigDelegate3;
  private SwigDelegateITapQuoteAPI_4 swigDelegate4;
  private SwigDelegateITapQuoteAPI_5 swigDelegate5;
  private SwigDelegateITapQuoteAPI_6 swigDelegate6;
  private SwigDelegateITapQuoteAPI_7 swigDelegate7;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(ITapQuoteAPINotify) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(string), typeof(ushort) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(TapAPIQuoteLoginAuth) };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] { typeof(uint).MakeByRefType() };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPICommodity) };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIContract) };
  private static global::System.Type[] swigMethodTypes7 = new global::System.Type[] { typeof(uint).MakeByRefType(), typeof(TapAPIContract) };
}

}
