//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeAPI {

public class ITapTradeAPI : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ITapTradeAPI(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ITapTradeAPI obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ITapTradeAPI obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ITapTradeAPI() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeAPIWrapperPINVOKE.delete_ITapTradeAPI(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public virtual int SetAPINotify(ITapTradeAPINotify pSpi) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_SetAPINotify(swigCPtr, ITapTradeAPINotify.getCPtr(pSpi));
    return ret;
  }

  public virtual int SetHostAddress(string IP, ushort port, bool bSSL) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_SetHostAddress__SWIG_0(swigCPtr, IP, port, bSSL);
    return ret;
  }

  public virtual int SetHostAddress(string IP, ushort port) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_SetHostAddress__SWIG_1(swigCPtr, IP, port);
    return ret;
  }

  public virtual int Login(TapAPITradeLoginAuth loginAuth) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_Login(swigCPtr, TapAPITradeLoginAuth.getCPtr(loginAuth));
    return ret;
  }

  public virtual int RequestVertificateCode(SWIGTYPE_p_unsigned_int sessionID, string ContactInfo) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_RequestVertificateCode(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), ContactInfo);
    return ret;
  }

  public virtual int SetVertificateCode(SWIGTYPE_p_unsigned_int sessionID, TapAPISecondCertificationReq req) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_SetVertificateCode(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPISecondCertificationReq.getCPtr(req));
    return ret;
  }

  public virtual int Disconnect() {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_Disconnect(swigCPtr);
    return ret;
  }

  public virtual int ChangePassword(SWIGTYPE_p_unsigned_int sessionID, TapAPIChangePasswordReq req) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_ChangePassword(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIChangePasswordReq.getCPtr(req));
    return ret;
  }

  public virtual int AuthPassword(SWIGTYPE_p_unsigned_int sessionID, TapAPIAuthPasswordReq req) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_AuthPassword(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAuthPasswordReq.getCPtr(req));
    return ret;
  }

  public virtual int HaveCertainRight(int rightID) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_HaveCertainRight(swigCPtr, rightID);
    return ret;
  }

  public virtual int QryTradingDate(SWIGTYPE_p_unsigned_int sessionID) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryTradingDate(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID));
    return ret;
  }

  public virtual int SetReservedInfo(SWIGTYPE_p_unsigned_int sessionID, string info) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_SetReservedInfo(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), info);
    return ret;
  }

  public virtual int QryAccount(SWIGTYPE_p_unsigned_int sessionID, TapAPIAccQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryAccount(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryFund(SWIGTYPE_p_unsigned_int sessionID, TapAPIFundReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryFund(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIFundReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryExchange(SWIGTYPE_p_unsigned_int sessionID) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryExchange(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID));
    return ret;
  }

  public virtual int QryCommodity(SWIGTYPE_p_unsigned_int sessionID) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryCommodity(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID));
    return ret;
  }

  public virtual int QryContract(SWIGTYPE_p_unsigned_int sessionID, TapAPICommodity qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryContract(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPICommodity.getCPtr(qryReq));
    return ret;
  }

  public virtual int InsertOrder(SWIGTYPE_p_unsigned_int sessionID, SWIGTYPE_p_a_51__char ClientOrderNo, TapAPINewOrder order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_InsertOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), SWIGTYPE_p_a_51__char.getCPtr(ClientOrderNo), TapAPINewOrder.getCPtr(order));
    return ret;
  }

  public virtual int CancelOrder(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderCancelReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_CancelOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderCancelReq.getCPtr(order));
    return ret;
  }

  public virtual int AmendOrder(SWIGTYPE_p_unsigned_int sessionID, TapAPIAmendOrder order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_AmendOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAmendOrder.getCPtr(order));
    return ret;
  }

  public virtual int ActivateOrder(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderCancelReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_ActivateOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderCancelReq.getCPtr(order));
    return ret;
  }

  public virtual int QryOrder(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryOrderProcess(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderProcessQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryOrderProcess(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderProcessQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryFill(SWIGTYPE_p_unsigned_int sessionID, TapAPIFillQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryFill(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIFillQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryPosition(SWIGTYPE_p_unsigned_int sessionID, TapAPIPositionQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryPosition(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIPositionQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryPositionSummary(SWIGTYPE_p_unsigned_int sessionID, TapAPIPositionQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryPositionSummary(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIPositionQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryCurrency(SWIGTYPE_p_unsigned_int sessionID) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryCurrency(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID));
    return ret;
  }

  public virtual int QryAccountCashAdjust(SWIGTYPE_p_unsigned_int sessionID, TapAPIAccountCashAdjustQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryAccountCashAdjust(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountCashAdjustQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryTradeMessage(SWIGTYPE_p_unsigned_int sessionID, TapAPITradeMessageReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryTradeMessage(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPITradeMessageReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryBill(SWIGTYPE_p_unsigned_int sessionID, TapAPIBillQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryBill(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIBillQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisOrder(SWIGTYPE_p_unsigned_int sessionID, TapAPIHisOrderQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryHisOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisOrderQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisOrderProcess(SWIGTYPE_p_unsigned_int sessionID, TapAPIHisOrderProcessQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryHisOrderProcess(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisOrderProcessQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisMatch(SWIGTYPE_p_unsigned_int sessionID, TapAPIHisMatchQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryHisMatch(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisMatchQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisPosition(SWIGTYPE_p_unsigned_int sessionID, TapAPIHisPositionQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryHisPosition(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisPositionQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryHisDelivery(SWIGTYPE_p_unsigned_int sessionID, TapAPIHisDeliveryQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryHisDelivery(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIHisDeliveryQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryAccountFeeRent(SWIGTYPE_p_unsigned_int sessionID, TapAPIAccountFeeRentQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryAccountFeeRent(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountFeeRentQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryAccountMarginRent(SWIGTYPE_p_unsigned_int sessionID, TapAPIAccountMarginRentQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryAccountMarginRent(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountMarginRentQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int InsertHKMarketOrder(SWIGTYPE_p_unsigned_int sessionID, SWIGTYPE_p_a_51__char ClientBuyOrderNo, SWIGTYPE_p_a_51__char ClientSellOrderNo, TapAPIOrderMarketInsertReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_InsertHKMarketOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), SWIGTYPE_p_a_51__char.getCPtr(ClientBuyOrderNo), SWIGTYPE_p_a_51__char.getCPtr(ClientSellOrderNo), TapAPIOrderMarketInsertReq.getCPtr(order));
    return ret;
  }

  public virtual int CancelHKMarketOrder(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderMarketDeleteReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_CancelHKMarketOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderMarketDeleteReq.getCPtr(order));
    return ret;
  }

  public virtual int OrderLocalRemove(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderLocalRemoveReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_OrderLocalRemove(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderLocalRemoveReq.getCPtr(order));
    return ret;
  }

  public virtual int OrderLocalInput(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderLocalInputReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_OrderLocalInput(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderLocalInputReq.getCPtr(order));
    return ret;
  }

  public virtual int OrderLocalModify(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderLocalModifyReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_OrderLocalModify(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderLocalModifyReq.getCPtr(order));
    return ret;
  }

  public virtual int OrderLocalTransfer(SWIGTYPE_p_unsigned_int sessionID, TapAPIOrderLocalTransferReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_OrderLocalTransfer(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIOrderLocalTransferReq.getCPtr(order));
    return ret;
  }

  public virtual int FillLocalInput(SWIGTYPE_p_unsigned_int sessionID, TapAPIFillLocalInputReq fill) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_FillLocalInput(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIFillLocalInputReq.getCPtr(fill));
    return ret;
  }

  public virtual int FillLocalRemove(SWIGTYPE_p_unsigned_int sessionID, TapAPIFillLocalRemoveReq fill) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_FillLocalRemove(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIFillLocalRemoveReq.getCPtr(fill));
    return ret;
  }

  public virtual int QrySpotLock(SWIGTYPE_p_unsigned_int sessionID, TapAPISpotLockQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QrySpotLock(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPISpotLockQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int SubmitUserLoginInfo(SWIGTYPE_p_unsigned_int sessionID, TapAPISubmitUserLoginInfo qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_SubmitUserLoginInfo(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPISubmitUserLoginInfo.getCPtr(qryReq));
    return ret;
  }

  public virtual int InsertSpecialOrder(SWIGTYPE_p_unsigned_int sessionID, SWIGTYPE_p_a_51__char clientorderno, TapAPISpecialOrderInsertReq order) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_InsertSpecialOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), SWIGTYPE_p_a_51__char.getCPtr(clientorderno), TapAPISpecialOrderInsertReq.getCPtr(order));
    return ret;
  }

  public virtual int QrySpecialOrder(SWIGTYPE_p_unsigned_int sessionID, TapAPISpecialOrderQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QrySpecialOrder(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPISpecialOrderQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryCombinePosition(SWIGTYPE_p_unsigned_int sessionID, TapAPICombinePositionQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryCombinePosition(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPICombinePositionQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryUserTrustDevice(SWIGTYPE_p_unsigned_int sessionID, TapAPIUserTrustDeviceQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryUserTrustDevice(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIUserTrustDeviceQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int AddUserTrustDevice(SWIGTYPE_p_unsigned_int sessionID, TapAPIUserTrustDeviceAddReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_AddUserTrustDevice(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIUserTrustDeviceAddReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int DelUserTrustDevice(SWIGTYPE_p_unsigned_int sessionID, TapAPIUserTrustDeviceDelReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_DelUserTrustDevice(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIUserTrustDeviceDelReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryIPOInfo(SWIGTYPE_p_unsigned_int sessionID, TapAPIIPOInfoQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryIPOInfo(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIIPOInfoQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryIPOStockQty(SWIGTYPE_p_unsigned_int sessionID, TapAPIAvailableApplyQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryIPOStockQty(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAvailableApplyQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int QryAccountIPO(SWIGTYPE_p_unsigned_int sessionID, TapAPIAccountIPOQryReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_QryAccountIPO(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountIPOQryReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int AddAccountIPO(SWIGTYPE_p_unsigned_int sessionID, TapAPIAccountIPOAddReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_AddAccountIPO(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountIPOAddReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int CancelAccountIPO(SWIGTYPE_p_unsigned_int sessionID, TapAPIAccountIPOCancelReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_CancelAccountIPO(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIAccountIPOCancelReq.getCPtr(qryReq));
    return ret;
  }

  public virtual int UnFreeze(TapAPITradeLoginAuth loginAuth) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_UnFreeze(swigCPtr, TapAPITradeLoginAuth.getCPtr(loginAuth));
    return ret;
  }

  public virtual int VerificateUnFreezeInfo(SWIGTYPE_p_unsigned_int sessionID, TapAPIVerifyIdentityReq qryReq) {
    int ret = TapTradeAPIWrapperPINVOKE.ITapTradeAPI_VerificateUnFreezeInfo(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(sessionID), TapAPIVerifyIdentityReq.getCPtr(qryReq));
    return ret;
  }

  public ITapTradeAPI() : this(TapTradeAPIWrapperPINVOKE.new_ITapTradeAPI(), true) {
    SwigDirectorConnect();
  }

  private void SwigDirectorConnect() {
    if (SwigDerivedClassHasMethod("SetAPINotify", swigMethodTypes0))
      swigDelegate0 = new SwigDelegateITapTradeAPI_0(SwigDirectorMethodSetAPINotify);
    if (SwigDerivedClassHasMethod("SetHostAddress", swigMethodTypes1))
      swigDelegate1 = new SwigDelegateITapTradeAPI_1(SwigDirectorMethodSetHostAddress__SWIG_0);
    if (SwigDerivedClassHasMethod("SetHostAddress", swigMethodTypes2))
      swigDelegate2 = new SwigDelegateITapTradeAPI_2(SwigDirectorMethodSetHostAddress__SWIG_1);
    if (SwigDerivedClassHasMethod("Login", swigMethodTypes3))
      swigDelegate3 = new SwigDelegateITapTradeAPI_3(SwigDirectorMethodLogin);
    if (SwigDerivedClassHasMethod("RequestVertificateCode", swigMethodTypes4))
      swigDelegate4 = new SwigDelegateITapTradeAPI_4(SwigDirectorMethodRequestVertificateCode);
    if (SwigDerivedClassHasMethod("SetVertificateCode", swigMethodTypes5))
      swigDelegate5 = new SwigDelegateITapTradeAPI_5(SwigDirectorMethodSetVertificateCode);
    if (SwigDerivedClassHasMethod("Disconnect", swigMethodTypes6))
      swigDelegate6 = new SwigDelegateITapTradeAPI_6(SwigDirectorMethodDisconnect);
    if (SwigDerivedClassHasMethod("ChangePassword", swigMethodTypes7))
      swigDelegate7 = new SwigDelegateITapTradeAPI_7(SwigDirectorMethodChangePassword);
    if (SwigDerivedClassHasMethod("AuthPassword", swigMethodTypes8))
      swigDelegate8 = new SwigDelegateITapTradeAPI_8(SwigDirectorMethodAuthPassword);
    if (SwigDerivedClassHasMethod("HaveCertainRight", swigMethodTypes9))
      swigDelegate9 = new SwigDelegateITapTradeAPI_9(SwigDirectorMethodHaveCertainRight);
    if (SwigDerivedClassHasMethod("QryTradingDate", swigMethodTypes10))
      swigDelegate10 = new SwigDelegateITapTradeAPI_10(SwigDirectorMethodQryTradingDate);
    if (SwigDerivedClassHasMethod("SetReservedInfo", swigMethodTypes11))
      swigDelegate11 = new SwigDelegateITapTradeAPI_11(SwigDirectorMethodSetReservedInfo);
    if (SwigDerivedClassHasMethod("QryAccount", swigMethodTypes12))
      swigDelegate12 = new SwigDelegateITapTradeAPI_12(SwigDirectorMethodQryAccount);
    if (SwigDerivedClassHasMethod("QryFund", swigMethodTypes13))
      swigDelegate13 = new SwigDelegateITapTradeAPI_13(SwigDirectorMethodQryFund);
    if (SwigDerivedClassHasMethod("QryExchange", swigMethodTypes14))
      swigDelegate14 = new SwigDelegateITapTradeAPI_14(SwigDirectorMethodQryExchange);
    if (SwigDerivedClassHasMethod("QryCommodity", swigMethodTypes15))
      swigDelegate15 = new SwigDelegateITapTradeAPI_15(SwigDirectorMethodQryCommodity);
    if (SwigDerivedClassHasMethod("QryContract", swigMethodTypes16))
      swigDelegate16 = new SwigDelegateITapTradeAPI_16(SwigDirectorMethodQryContract);
    if (SwigDerivedClassHasMethod("InsertOrder", swigMethodTypes17))
      swigDelegate17 = new SwigDelegateITapTradeAPI_17(SwigDirectorMethodInsertOrder);
    if (SwigDerivedClassHasMethod("CancelOrder", swigMethodTypes18))
      swigDelegate18 = new SwigDelegateITapTradeAPI_18(SwigDirectorMethodCancelOrder);
    if (SwigDerivedClassHasMethod("AmendOrder", swigMethodTypes19))
      swigDelegate19 = new SwigDelegateITapTradeAPI_19(SwigDirectorMethodAmendOrder);
    if (SwigDerivedClassHasMethod("ActivateOrder", swigMethodTypes20))
      swigDelegate20 = new SwigDelegateITapTradeAPI_20(SwigDirectorMethodActivateOrder);
    if (SwigDerivedClassHasMethod("QryOrder", swigMethodTypes21))
      swigDelegate21 = new SwigDelegateITapTradeAPI_21(SwigDirectorMethodQryOrder);
    if (SwigDerivedClassHasMethod("QryOrderProcess", swigMethodTypes22))
      swigDelegate22 = new SwigDelegateITapTradeAPI_22(SwigDirectorMethodQryOrderProcess);
    if (SwigDerivedClassHasMethod("QryFill", swigMethodTypes23))
      swigDelegate23 = new SwigDelegateITapTradeAPI_23(SwigDirectorMethodQryFill);
    if (SwigDerivedClassHasMethod("QryPosition", swigMethodTypes24))
      swigDelegate24 = new SwigDelegateITapTradeAPI_24(SwigDirectorMethodQryPosition);
    if (SwigDerivedClassHasMethod("QryPositionSummary", swigMethodTypes25))
      swigDelegate25 = new SwigDelegateITapTradeAPI_25(SwigDirectorMethodQryPositionSummary);
    if (SwigDerivedClassHasMethod("QryCurrency", swigMethodTypes26))
      swigDelegate26 = new SwigDelegateITapTradeAPI_26(SwigDirectorMethodQryCurrency);
    if (SwigDerivedClassHasMethod("QryAccountCashAdjust", swigMethodTypes27))
      swigDelegate27 = new SwigDelegateITapTradeAPI_27(SwigDirectorMethodQryAccountCashAdjust);
    if (SwigDerivedClassHasMethod("QryTradeMessage", swigMethodTypes28))
      swigDelegate28 = new SwigDelegateITapTradeAPI_28(SwigDirectorMethodQryTradeMessage);
    if (SwigDerivedClassHasMethod("QryBill", swigMethodTypes29))
      swigDelegate29 = new SwigDelegateITapTradeAPI_29(SwigDirectorMethodQryBill);
    if (SwigDerivedClassHasMethod("QryHisOrder", swigMethodTypes30))
      swigDelegate30 = new SwigDelegateITapTradeAPI_30(SwigDirectorMethodQryHisOrder);
    if (SwigDerivedClassHasMethod("QryHisOrderProcess", swigMethodTypes31))
      swigDelegate31 = new SwigDelegateITapTradeAPI_31(SwigDirectorMethodQryHisOrderProcess);
    if (SwigDerivedClassHasMethod("QryHisMatch", swigMethodTypes32))
      swigDelegate32 = new SwigDelegateITapTradeAPI_32(SwigDirectorMethodQryHisMatch);
    if (SwigDerivedClassHasMethod("QryHisPosition", swigMethodTypes33))
      swigDelegate33 = new SwigDelegateITapTradeAPI_33(SwigDirectorMethodQryHisPosition);
    if (SwigDerivedClassHasMethod("QryHisDelivery", swigMethodTypes34))
      swigDelegate34 = new SwigDelegateITapTradeAPI_34(SwigDirectorMethodQryHisDelivery);
    if (SwigDerivedClassHasMethod("QryAccountFeeRent", swigMethodTypes35))
      swigDelegate35 = new SwigDelegateITapTradeAPI_35(SwigDirectorMethodQryAccountFeeRent);
    if (SwigDerivedClassHasMethod("QryAccountMarginRent", swigMethodTypes36))
      swigDelegate36 = new SwigDelegateITapTradeAPI_36(SwigDirectorMethodQryAccountMarginRent);
    if (SwigDerivedClassHasMethod("InsertHKMarketOrder", swigMethodTypes37))
      swigDelegate37 = new SwigDelegateITapTradeAPI_37(SwigDirectorMethodInsertHKMarketOrder);
    if (SwigDerivedClassHasMethod("CancelHKMarketOrder", swigMethodTypes38))
      swigDelegate38 = new SwigDelegateITapTradeAPI_38(SwigDirectorMethodCancelHKMarketOrder);
    if (SwigDerivedClassHasMethod("OrderLocalRemove", swigMethodTypes39))
      swigDelegate39 = new SwigDelegateITapTradeAPI_39(SwigDirectorMethodOrderLocalRemove);
    if (SwigDerivedClassHasMethod("OrderLocalInput", swigMethodTypes40))
      swigDelegate40 = new SwigDelegateITapTradeAPI_40(SwigDirectorMethodOrderLocalInput);
    if (SwigDerivedClassHasMethod("OrderLocalModify", swigMethodTypes41))
      swigDelegate41 = new SwigDelegateITapTradeAPI_41(SwigDirectorMethodOrderLocalModify);
    if (SwigDerivedClassHasMethod("OrderLocalTransfer", swigMethodTypes42))
      swigDelegate42 = new SwigDelegateITapTradeAPI_42(SwigDirectorMethodOrderLocalTransfer);
    if (SwigDerivedClassHasMethod("FillLocalInput", swigMethodTypes43))
      swigDelegate43 = new SwigDelegateITapTradeAPI_43(SwigDirectorMethodFillLocalInput);
    if (SwigDerivedClassHasMethod("FillLocalRemove", swigMethodTypes44))
      swigDelegate44 = new SwigDelegateITapTradeAPI_44(SwigDirectorMethodFillLocalRemove);
    if (SwigDerivedClassHasMethod("QrySpotLock", swigMethodTypes45))
      swigDelegate45 = new SwigDelegateITapTradeAPI_45(SwigDirectorMethodQrySpotLock);
    if (SwigDerivedClassHasMethod("SubmitUserLoginInfo", swigMethodTypes46))
      swigDelegate46 = new SwigDelegateITapTradeAPI_46(SwigDirectorMethodSubmitUserLoginInfo);
    if (SwigDerivedClassHasMethod("InsertSpecialOrder", swigMethodTypes47))
      swigDelegate47 = new SwigDelegateITapTradeAPI_47(SwigDirectorMethodInsertSpecialOrder);
    if (SwigDerivedClassHasMethod("QrySpecialOrder", swigMethodTypes48))
      swigDelegate48 = new SwigDelegateITapTradeAPI_48(SwigDirectorMethodQrySpecialOrder);
    if (SwigDerivedClassHasMethod("QryCombinePosition", swigMethodTypes49))
      swigDelegate49 = new SwigDelegateITapTradeAPI_49(SwigDirectorMethodQryCombinePosition);
    if (SwigDerivedClassHasMethod("QryUserTrustDevice", swigMethodTypes50))
      swigDelegate50 = new SwigDelegateITapTradeAPI_50(SwigDirectorMethodQryUserTrustDevice);
    if (SwigDerivedClassHasMethod("AddUserTrustDevice", swigMethodTypes51))
      swigDelegate51 = new SwigDelegateITapTradeAPI_51(SwigDirectorMethodAddUserTrustDevice);
    if (SwigDerivedClassHasMethod("DelUserTrustDevice", swigMethodTypes52))
      swigDelegate52 = new SwigDelegateITapTradeAPI_52(SwigDirectorMethodDelUserTrustDevice);
    if (SwigDerivedClassHasMethod("QryIPOInfo", swigMethodTypes53))
      swigDelegate53 = new SwigDelegateITapTradeAPI_53(SwigDirectorMethodQryIPOInfo);
    if (SwigDerivedClassHasMethod("QryIPOStockQty", swigMethodTypes54))
      swigDelegate54 = new SwigDelegateITapTradeAPI_54(SwigDirectorMethodQryIPOStockQty);
    if (SwigDerivedClassHasMethod("QryAccountIPO", swigMethodTypes55))
      swigDelegate55 = new SwigDelegateITapTradeAPI_55(SwigDirectorMethodQryAccountIPO);
    if (SwigDerivedClassHasMethod("AddAccountIPO", swigMethodTypes56))
      swigDelegate56 = new SwigDelegateITapTradeAPI_56(SwigDirectorMethodAddAccountIPO);
    if (SwigDerivedClassHasMethod("CancelAccountIPO", swigMethodTypes57))
      swigDelegate57 = new SwigDelegateITapTradeAPI_57(SwigDirectorMethodCancelAccountIPO);
    if (SwigDerivedClassHasMethod("UnFreeze", swigMethodTypes58))
      swigDelegate58 = new SwigDelegateITapTradeAPI_58(SwigDirectorMethodUnFreeze);
    if (SwigDerivedClassHasMethod("VerificateUnFreezeInfo", swigMethodTypes59))
      swigDelegate59 = new SwigDelegateITapTradeAPI_59(SwigDirectorMethodVerificateUnFreezeInfo);
    TapTradeAPIWrapperPINVOKE.ITapTradeAPI_director_connect(swigCPtr, swigDelegate0, swigDelegate1, swigDelegate2, swigDelegate3, swigDelegate4, swigDelegate5, swigDelegate6, swigDelegate7, swigDelegate8, swigDelegate9, swigDelegate10, swigDelegate11, swigDelegate12, swigDelegate13, swigDelegate14, swigDelegate15, swigDelegate16, swigDelegate17, swigDelegate18, swigDelegate19, swigDelegate20, swigDelegate21, swigDelegate22, swigDelegate23, swigDelegate24, swigDelegate25, swigDelegate26, swigDelegate27, swigDelegate28, swigDelegate29, swigDelegate30, swigDelegate31, swigDelegate32, swigDelegate33, swigDelegate34, swigDelegate35, swigDelegate36, swigDelegate37, swigDelegate38, swigDelegate39, swigDelegate40, swigDelegate41, swigDelegate42, swigDelegate43, swigDelegate44, swigDelegate45, swigDelegate46, swigDelegate47, swigDelegate48, swigDelegate49, swigDelegate50, swigDelegate51, swigDelegate52, swigDelegate53, swigDelegate54, swigDelegate55, swigDelegate56, swigDelegate57, swigDelegate58, swigDelegate59);
  }

  private bool SwigDerivedClassHasMethod(string methodName, global::System.Type[] methodTypes) {
    global::System.Reflection.MethodInfo[] methodInfos = this.GetType().GetMethods(
        global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic | global::System.Reflection.BindingFlags.Instance);
    foreach (global::System.Reflection.MethodInfo methodInfo in methodInfos) {
      if (methodInfo.DeclaringType == null)
        continue;

      if (methodInfo.Name != methodName)
        continue;

      var parameters = methodInfo.GetParameters();
      if (parameters.Length != methodTypes.Length)
        continue;

      bool parametersMatch = true;
      for (var i = 0; i < parameters.Length; i++) {
        if (parameters[i].ParameterType != methodTypes[i]) {
          parametersMatch = false;
          break;
        }
      }

      if (!parametersMatch)
        continue;

      if (methodInfo.IsVirtual && (methodInfo.DeclaringType.IsSubclassOf(typeof(ITapTradeAPI))) &&
        methodInfo.DeclaringType != methodInfo.GetBaseDefinition().DeclaringType) {
        return true;
      }
    }

    return false;
  }

  private int SwigDirectorMethodSetAPINotify(global::System.IntPtr pSpi) {
    return SetAPINotify((pSpi == global::System.IntPtr.Zero) ? null : new ITapTradeAPINotify(pSpi, false));
  }

  private int SwigDirectorMethodSetHostAddress__SWIG_0(string IP, ushort port, bool bSSL) {
    return SetHostAddress(IP, port, bSSL);
  }

  private int SwigDirectorMethodSetHostAddress__SWIG_1(string IP, ushort port) {
    return SetHostAddress(IP, port);
  }

  private int SwigDirectorMethodLogin(global::System.IntPtr loginAuth) {
    return Login((loginAuth == global::System.IntPtr.Zero) ? null : new TapAPITradeLoginAuth(loginAuth, false));
  }

  private int SwigDirectorMethodRequestVertificateCode(global::System.IntPtr sessionID, string ContactInfo) {
    return RequestVertificateCode((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), ContactInfo);
  }

  private int SwigDirectorMethodSetVertificateCode(global::System.IntPtr sessionID, global::System.IntPtr req) {
    return SetVertificateCode((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (req == global::System.IntPtr.Zero) ? null : new TapAPISecondCertificationReq(req, false));
  }

  private int SwigDirectorMethodDisconnect() {
    return Disconnect();
  }

  private int SwigDirectorMethodChangePassword(global::System.IntPtr sessionID, global::System.IntPtr req) {
    return ChangePassword((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (req == global::System.IntPtr.Zero) ? null : new TapAPIChangePasswordReq(req, false));
  }

  private int SwigDirectorMethodAuthPassword(global::System.IntPtr sessionID, global::System.IntPtr req) {
    return AuthPassword((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (req == global::System.IntPtr.Zero) ? null : new TapAPIAuthPasswordReq(req, false));
  }

  private int SwigDirectorMethodHaveCertainRight(int rightID) {
    return HaveCertainRight(rightID);
  }

  private int SwigDirectorMethodQryTradingDate(global::System.IntPtr sessionID) {
    return QryTradingDate((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false));
  }

  private int SwigDirectorMethodSetReservedInfo(global::System.IntPtr sessionID, string info) {
    return SetReservedInfo((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), info);
  }

  private int SwigDirectorMethodQryAccount(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryAccount((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryFund(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryFund((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIFundReq(qryReq, false));
  }

  private int SwigDirectorMethodQryExchange(global::System.IntPtr sessionID) {
    return QryExchange((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false));
  }

  private int SwigDirectorMethodQryCommodity(global::System.IntPtr sessionID) {
    return QryCommodity((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false));
  }

  private int SwigDirectorMethodQryContract(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryContract((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPICommodity(qryReq, false));
  }

  private int SwigDirectorMethodInsertOrder(global::System.IntPtr sessionID, global::System.IntPtr ClientOrderNo, global::System.IntPtr order) {
    return InsertOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (ClientOrderNo == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_51__char(ClientOrderNo, false), (order == global::System.IntPtr.Zero) ? null : new TapAPINewOrder(order, false));
  }

  private int SwigDirectorMethodCancelOrder(global::System.IntPtr sessionID, global::System.IntPtr order) {
    return CancelOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderCancelReq(order, false));
  }

  private int SwigDirectorMethodAmendOrder(global::System.IntPtr sessionID, global::System.IntPtr order) {
    return AmendOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIAmendOrder(order, false));
  }

  private int SwigDirectorMethodActivateOrder(global::System.IntPtr sessionID, global::System.IntPtr order) {
    return ActivateOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderCancelReq(order, false));
  }

  private int SwigDirectorMethodQryOrder(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIOrderQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryOrderProcess(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryOrderProcess((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIOrderProcessQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryFill(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryFill((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIFillQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryPosition(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryPosition((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIPositionQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryPositionSummary(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryPositionSummary((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIPositionQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryCurrency(global::System.IntPtr sessionID) {
    return QryCurrency((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false));
  }

  private int SwigDirectorMethodQryAccountCashAdjust(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryAccountCashAdjust((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountCashAdjustQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryTradeMessage(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryTradeMessage((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPITradeMessageReq(qryReq, false));
  }

  private int SwigDirectorMethodQryBill(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryBill((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIBillQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisOrder(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryHisOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisOrderQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisOrderProcess(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryHisOrderProcess((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisOrderProcessQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisMatch(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryHisMatch((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisMatchQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisPosition(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryHisPosition((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisPositionQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryHisDelivery(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryHisDelivery((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIHisDeliveryQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryAccountFeeRent(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryAccountFeeRent((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountFeeRentQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryAccountMarginRent(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryAccountMarginRent((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountMarginRentQryReq(qryReq, false));
  }

  private int SwigDirectorMethodInsertHKMarketOrder(global::System.IntPtr sessionID, global::System.IntPtr ClientBuyOrderNo, global::System.IntPtr ClientSellOrderNo, global::System.IntPtr order) {
    return InsertHKMarketOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (ClientBuyOrderNo == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_51__char(ClientBuyOrderNo, false), (ClientSellOrderNo == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_51__char(ClientSellOrderNo, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderMarketInsertReq(order, false));
  }

  private int SwigDirectorMethodCancelHKMarketOrder(global::System.IntPtr sessionID, global::System.IntPtr order) {
    return CancelHKMarketOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderMarketDeleteReq(order, false));
  }

  private int SwigDirectorMethodOrderLocalRemove(global::System.IntPtr sessionID, global::System.IntPtr order) {
    return OrderLocalRemove((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderLocalRemoveReq(order, false));
  }

  private int SwigDirectorMethodOrderLocalInput(global::System.IntPtr sessionID, global::System.IntPtr order) {
    return OrderLocalInput((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderLocalInputReq(order, false));
  }

  private int SwigDirectorMethodOrderLocalModify(global::System.IntPtr sessionID, global::System.IntPtr order) {
    return OrderLocalModify((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderLocalModifyReq(order, false));
  }

  private int SwigDirectorMethodOrderLocalTransfer(global::System.IntPtr sessionID, global::System.IntPtr order) {
    return OrderLocalTransfer((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (order == global::System.IntPtr.Zero) ? null : new TapAPIOrderLocalTransferReq(order, false));
  }

  private int SwigDirectorMethodFillLocalInput(global::System.IntPtr sessionID, global::System.IntPtr fill) {
    return FillLocalInput((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (fill == global::System.IntPtr.Zero) ? null : new TapAPIFillLocalInputReq(fill, false));
  }

  private int SwigDirectorMethodFillLocalRemove(global::System.IntPtr sessionID, global::System.IntPtr fill) {
    return FillLocalRemove((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (fill == global::System.IntPtr.Zero) ? null : new TapAPIFillLocalRemoveReq(fill, false));
  }

  private int SwigDirectorMethodQrySpotLock(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QrySpotLock((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPISpotLockQryReq(qryReq, false));
  }

  private int SwigDirectorMethodSubmitUserLoginInfo(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return SubmitUserLoginInfo((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPISubmitUserLoginInfo(qryReq, false));
  }

  private int SwigDirectorMethodInsertSpecialOrder(global::System.IntPtr sessionID, global::System.IntPtr clientorderno, global::System.IntPtr order) {
    return InsertSpecialOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (clientorderno == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_51__char(clientorderno, false), (order == global::System.IntPtr.Zero) ? null : new TapAPISpecialOrderInsertReq(order, false));
  }

  private int SwigDirectorMethodQrySpecialOrder(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QrySpecialOrder((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPISpecialOrderQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryCombinePosition(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryCombinePosition((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPICombinePositionQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryUserTrustDevice(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryUserTrustDevice((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIUserTrustDeviceQryReq(qryReq, false));
  }

  private int SwigDirectorMethodAddUserTrustDevice(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return AddUserTrustDevice((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIUserTrustDeviceAddReq(qryReq, false));
  }

  private int SwigDirectorMethodDelUserTrustDevice(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return DelUserTrustDevice((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIUserTrustDeviceDelReq(qryReq, false));
  }

  private int SwigDirectorMethodQryIPOInfo(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryIPOInfo((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIIPOInfoQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryIPOStockQty(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryIPOStockQty((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAvailableApplyQryReq(qryReq, false));
  }

  private int SwigDirectorMethodQryAccountIPO(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return QryAccountIPO((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountIPOQryReq(qryReq, false));
  }

  private int SwigDirectorMethodAddAccountIPO(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return AddAccountIPO((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountIPOAddReq(qryReq, false));
  }

  private int SwigDirectorMethodCancelAccountIPO(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return CancelAccountIPO((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIAccountIPOCancelReq(qryReq, false));
  }

  private int SwigDirectorMethodUnFreeze(global::System.IntPtr loginAuth) {
    return UnFreeze((loginAuth == global::System.IntPtr.Zero) ? null : new TapAPITradeLoginAuth(loginAuth, false));
  }

  private int SwigDirectorMethodVerificateUnFreezeInfo(global::System.IntPtr sessionID, global::System.IntPtr qryReq) {
    return VerificateUnFreezeInfo((sessionID == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(sessionID, false), (qryReq == global::System.IntPtr.Zero) ? null : new TapAPIVerifyIdentityReq(qryReq, false));
  }

  public delegate int SwigDelegateITapTradeAPI_0(global::System.IntPtr pSpi);
  public delegate int SwigDelegateITapTradeAPI_1(string IP, ushort port, bool bSSL);
  public delegate int SwigDelegateITapTradeAPI_2(string IP, ushort port);
  public delegate int SwigDelegateITapTradeAPI_3(global::System.IntPtr loginAuth);
  public delegate int SwigDelegateITapTradeAPI_4(global::System.IntPtr sessionID, string ContactInfo);
  public delegate int SwigDelegateITapTradeAPI_5(global::System.IntPtr sessionID, global::System.IntPtr req);
  public delegate int SwigDelegateITapTradeAPI_6();
  public delegate int SwigDelegateITapTradeAPI_7(global::System.IntPtr sessionID, global::System.IntPtr req);
  public delegate int SwigDelegateITapTradeAPI_8(global::System.IntPtr sessionID, global::System.IntPtr req);
  public delegate int SwigDelegateITapTradeAPI_9(int rightID);
  public delegate int SwigDelegateITapTradeAPI_10(global::System.IntPtr sessionID);
  public delegate int SwigDelegateITapTradeAPI_11(global::System.IntPtr sessionID, string info);
  public delegate int SwigDelegateITapTradeAPI_12(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_13(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_14(global::System.IntPtr sessionID);
  public delegate int SwigDelegateITapTradeAPI_15(global::System.IntPtr sessionID);
  public delegate int SwigDelegateITapTradeAPI_16(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_17(global::System.IntPtr sessionID, global::System.IntPtr ClientOrderNo, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_18(global::System.IntPtr sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_19(global::System.IntPtr sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_20(global::System.IntPtr sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_21(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_22(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_23(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_24(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_25(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_26(global::System.IntPtr sessionID);
  public delegate int SwigDelegateITapTradeAPI_27(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_28(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_29(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_30(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_31(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_32(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_33(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_34(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_35(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_36(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_37(global::System.IntPtr sessionID, global::System.IntPtr ClientBuyOrderNo, global::System.IntPtr ClientSellOrderNo, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_38(global::System.IntPtr sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_39(global::System.IntPtr sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_40(global::System.IntPtr sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_41(global::System.IntPtr sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_42(global::System.IntPtr sessionID, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_43(global::System.IntPtr sessionID, global::System.IntPtr fill);
  public delegate int SwigDelegateITapTradeAPI_44(global::System.IntPtr sessionID, global::System.IntPtr fill);
  public delegate int SwigDelegateITapTradeAPI_45(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_46(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_47(global::System.IntPtr sessionID, global::System.IntPtr clientorderno, global::System.IntPtr order);
  public delegate int SwigDelegateITapTradeAPI_48(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_49(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_50(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_51(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_52(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_53(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_54(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_55(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_56(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_57(global::System.IntPtr sessionID, global::System.IntPtr qryReq);
  public delegate int SwigDelegateITapTradeAPI_58(global::System.IntPtr loginAuth);
  public delegate int SwigDelegateITapTradeAPI_59(global::System.IntPtr sessionID, global::System.IntPtr qryReq);

  private SwigDelegateITapTradeAPI_0 swigDelegate0;
  private SwigDelegateITapTradeAPI_1 swigDelegate1;
  private SwigDelegateITapTradeAPI_2 swigDelegate2;
  private SwigDelegateITapTradeAPI_3 swigDelegate3;
  private SwigDelegateITapTradeAPI_4 swigDelegate4;
  private SwigDelegateITapTradeAPI_5 swigDelegate5;
  private SwigDelegateITapTradeAPI_6 swigDelegate6;
  private SwigDelegateITapTradeAPI_7 swigDelegate7;
  private SwigDelegateITapTradeAPI_8 swigDelegate8;
  private SwigDelegateITapTradeAPI_9 swigDelegate9;
  private SwigDelegateITapTradeAPI_10 swigDelegate10;
  private SwigDelegateITapTradeAPI_11 swigDelegate11;
  private SwigDelegateITapTradeAPI_12 swigDelegate12;
  private SwigDelegateITapTradeAPI_13 swigDelegate13;
  private SwigDelegateITapTradeAPI_14 swigDelegate14;
  private SwigDelegateITapTradeAPI_15 swigDelegate15;
  private SwigDelegateITapTradeAPI_16 swigDelegate16;
  private SwigDelegateITapTradeAPI_17 swigDelegate17;
  private SwigDelegateITapTradeAPI_18 swigDelegate18;
  private SwigDelegateITapTradeAPI_19 swigDelegate19;
  private SwigDelegateITapTradeAPI_20 swigDelegate20;
  private SwigDelegateITapTradeAPI_21 swigDelegate21;
  private SwigDelegateITapTradeAPI_22 swigDelegate22;
  private SwigDelegateITapTradeAPI_23 swigDelegate23;
  private SwigDelegateITapTradeAPI_24 swigDelegate24;
  private SwigDelegateITapTradeAPI_25 swigDelegate25;
  private SwigDelegateITapTradeAPI_26 swigDelegate26;
  private SwigDelegateITapTradeAPI_27 swigDelegate27;
  private SwigDelegateITapTradeAPI_28 swigDelegate28;
  private SwigDelegateITapTradeAPI_29 swigDelegate29;
  private SwigDelegateITapTradeAPI_30 swigDelegate30;
  private SwigDelegateITapTradeAPI_31 swigDelegate31;
  private SwigDelegateITapTradeAPI_32 swigDelegate32;
  private SwigDelegateITapTradeAPI_33 swigDelegate33;
  private SwigDelegateITapTradeAPI_34 swigDelegate34;
  private SwigDelegateITapTradeAPI_35 swigDelegate35;
  private SwigDelegateITapTradeAPI_36 swigDelegate36;
  private SwigDelegateITapTradeAPI_37 swigDelegate37;
  private SwigDelegateITapTradeAPI_38 swigDelegate38;
  private SwigDelegateITapTradeAPI_39 swigDelegate39;
  private SwigDelegateITapTradeAPI_40 swigDelegate40;
  private SwigDelegateITapTradeAPI_41 swigDelegate41;
  private SwigDelegateITapTradeAPI_42 swigDelegate42;
  private SwigDelegateITapTradeAPI_43 swigDelegate43;
  private SwigDelegateITapTradeAPI_44 swigDelegate44;
  private SwigDelegateITapTradeAPI_45 swigDelegate45;
  private SwigDelegateITapTradeAPI_46 swigDelegate46;
  private SwigDelegateITapTradeAPI_47 swigDelegate47;
  private SwigDelegateITapTradeAPI_48 swigDelegate48;
  private SwigDelegateITapTradeAPI_49 swigDelegate49;
  private SwigDelegateITapTradeAPI_50 swigDelegate50;
  private SwigDelegateITapTradeAPI_51 swigDelegate51;
  private SwigDelegateITapTradeAPI_52 swigDelegate52;
  private SwigDelegateITapTradeAPI_53 swigDelegate53;
  private SwigDelegateITapTradeAPI_54 swigDelegate54;
  private SwigDelegateITapTradeAPI_55 swigDelegate55;
  private SwigDelegateITapTradeAPI_56 swigDelegate56;
  private SwigDelegateITapTradeAPI_57 swigDelegate57;
  private SwigDelegateITapTradeAPI_58 swigDelegate58;
  private SwigDelegateITapTradeAPI_59 swigDelegate59;

  private static global::System.Type[] swigMethodTypes0 = new global::System.Type[] { typeof(ITapTradeAPINotify) };
  private static global::System.Type[] swigMethodTypes1 = new global::System.Type[] { typeof(string), typeof(ushort), typeof(bool) };
  private static global::System.Type[] swigMethodTypes2 = new global::System.Type[] { typeof(string), typeof(ushort) };
  private static global::System.Type[] swigMethodTypes3 = new global::System.Type[] { typeof(TapAPITradeLoginAuth) };
  private static global::System.Type[] swigMethodTypes4 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(string) };
  private static global::System.Type[] swigMethodTypes5 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPISecondCertificationReq) };
  private static global::System.Type[] swigMethodTypes6 = new global::System.Type[] {  };
  private static global::System.Type[] swigMethodTypes7 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIChangePasswordReq) };
  private static global::System.Type[] swigMethodTypes8 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAuthPasswordReq) };
  private static global::System.Type[] swigMethodTypes9 = new global::System.Type[] { typeof(int) };
  private static global::System.Type[] swigMethodTypes10 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int) };
  private static global::System.Type[] swigMethodTypes11 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(string) };
  private static global::System.Type[] swigMethodTypes12 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAccQryReq) };
  private static global::System.Type[] swigMethodTypes13 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIFundReq) };
  private static global::System.Type[] swigMethodTypes14 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int) };
  private static global::System.Type[] swigMethodTypes15 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int) };
  private static global::System.Type[] swigMethodTypes16 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPICommodity) };
  private static global::System.Type[] swigMethodTypes17 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(SWIGTYPE_p_a_51__char), typeof(TapAPINewOrder) };
  private static global::System.Type[] swigMethodTypes18 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderCancelReq) };
  private static global::System.Type[] swigMethodTypes19 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAmendOrder) };
  private static global::System.Type[] swigMethodTypes20 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderCancelReq) };
  private static global::System.Type[] swigMethodTypes21 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderQryReq) };
  private static global::System.Type[] swigMethodTypes22 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderProcessQryReq) };
  private static global::System.Type[] swigMethodTypes23 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIFillQryReq) };
  private static global::System.Type[] swigMethodTypes24 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIPositionQryReq) };
  private static global::System.Type[] swigMethodTypes25 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIPositionQryReq) };
  private static global::System.Type[] swigMethodTypes26 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int) };
  private static global::System.Type[] swigMethodTypes27 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAccountCashAdjustQryReq) };
  private static global::System.Type[] swigMethodTypes28 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPITradeMessageReq) };
  private static global::System.Type[] swigMethodTypes29 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIBillQryReq) };
  private static global::System.Type[] swigMethodTypes30 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIHisOrderQryReq) };
  private static global::System.Type[] swigMethodTypes31 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIHisOrderProcessQryReq) };
  private static global::System.Type[] swigMethodTypes32 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIHisMatchQryReq) };
  private static global::System.Type[] swigMethodTypes33 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIHisPositionQryReq) };
  private static global::System.Type[] swigMethodTypes34 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIHisDeliveryQryReq) };
  private static global::System.Type[] swigMethodTypes35 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAccountFeeRentQryReq) };
  private static global::System.Type[] swigMethodTypes36 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAccountMarginRentQryReq) };
  private static global::System.Type[] swigMethodTypes37 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(SWIGTYPE_p_a_51__char), typeof(SWIGTYPE_p_a_51__char), typeof(TapAPIOrderMarketInsertReq) };
  private static global::System.Type[] swigMethodTypes38 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderMarketDeleteReq) };
  private static global::System.Type[] swigMethodTypes39 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderLocalRemoveReq) };
  private static global::System.Type[] swigMethodTypes40 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderLocalInputReq) };
  private static global::System.Type[] swigMethodTypes41 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderLocalModifyReq) };
  private static global::System.Type[] swigMethodTypes42 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIOrderLocalTransferReq) };
  private static global::System.Type[] swigMethodTypes43 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIFillLocalInputReq) };
  private static global::System.Type[] swigMethodTypes44 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIFillLocalRemoveReq) };
  private static global::System.Type[] swigMethodTypes45 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPISpotLockQryReq) };
  private static global::System.Type[] swigMethodTypes46 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPISubmitUserLoginInfo) };
  private static global::System.Type[] swigMethodTypes47 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(SWIGTYPE_p_a_51__char), typeof(TapAPISpecialOrderInsertReq) };
  private static global::System.Type[] swigMethodTypes48 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPISpecialOrderQryReq) };
  private static global::System.Type[] swigMethodTypes49 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPICombinePositionQryReq) };
  private static global::System.Type[] swigMethodTypes50 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIUserTrustDeviceQryReq) };
  private static global::System.Type[] swigMethodTypes51 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIUserTrustDeviceAddReq) };
  private static global::System.Type[] swigMethodTypes52 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIUserTrustDeviceDelReq) };
  private static global::System.Type[] swigMethodTypes53 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIIPOInfoQryReq) };
  private static global::System.Type[] swigMethodTypes54 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAvailableApplyQryReq) };
  private static global::System.Type[] swigMethodTypes55 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAccountIPOQryReq) };
  private static global::System.Type[] swigMethodTypes56 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAccountIPOAddReq) };
  private static global::System.Type[] swigMethodTypes57 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIAccountIPOCancelReq) };
  private static global::System.Type[] swigMethodTypes58 = new global::System.Type[] { typeof(TapAPITradeLoginAuth) };
  private static global::System.Type[] swigMethodTypes59 = new global::System.Type[] { typeof(SWIGTYPE_p_unsigned_int), typeof(TapAPIVerifyIdentityReq) };
}

}
