//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeAPI {

public class TapAPISpecialOrderInfo : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPISpecialOrderInfo(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPISpecialOrderInfo obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPISpecialOrderInfo obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPISpecialOrderInfo() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeAPIWrapperPINVOKE.delete_TapAPISpecialOrderInfo(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint SessionID {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_SessionID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_SessionID_get(swigCPtr);
      return ret;
    } 
  }

  public uint ErrorCode {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ErrorCode_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorText {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ErrorText_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ErrorText_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientOrderNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ClientOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ClientOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public char SpecialOrderType {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_SpecialOrderType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_SpecialOrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public string CombineStrategy {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CombineStrategy_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CombineStrategy_get(swigCPtr);
      return ret;
    } 
  }

  public string CombineNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CombineNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CombineNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderQty {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderQty_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide1 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderSide1_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderSide1_get(swigCPtr);
      return ret;
    } 
  }

  public uint CombineQty1 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CombineQty1_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CombineQty1_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag1 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_HedgeFlag1_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_HedgeFlag1_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo2 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ContractNo2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ContractNo2_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice2 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_StrikePrice2_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_StrikePrice2_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag2 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CallOrPutFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CallOrPutFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSide2 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderSide2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderSide2_get(swigCPtr);
      return ret;
    } 
  }

  public uint CombineQty2 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CombineQty2_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_CombineQty2_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag2 {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_HedgeFlag2_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_HedgeFlag2_get(swigCPtr);
      return ret;
    } 
  }

  public string LicenseNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_LicenseNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_LicenseNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientLocalIP {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ClientLocalIP_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ClientLocalIP_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientMac {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ClientMac_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ClientMac_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientIP {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ClientIP_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_ClientIP_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderStreamID {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperChannelNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_UpperChannelNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_UpperChannelNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderLocalNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderLocalNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderLocalNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderSystemNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderExchangeSystemNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderExchangeSystemNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderExchangeSystemNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderInsertUserNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderInsertUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderInsertUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderInsertTime {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderInsertTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderInsertTime_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderState {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderState_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPISpecialOrderInfo_OrderState_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPISpecialOrderInfo() : this(TapTradeAPIWrapperPINVOKE.new_TapAPISpecialOrderInfo(), true) {
  }

}

}
