//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeAPI {

public class TapAPIOrderMarketInsertRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIOrderMarketInsertRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIOrderMarketInsertRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIOrderMarketInsertRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIOrderMarketInsertRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeAPIWrapperPINVOKE.delete_TapAPIOrderMarketInsertRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string AccountNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderType {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderType_get(swigCPtr);
      return ret;
    } 
  }

  public char TimeInForce {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_TimeInForce_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_TimeInForce_get(swigCPtr);
      return ret;
    } 
  }

  public string ExpireTime {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ExpireTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ExpireTime_get(swigCPtr);
      return ret;
    } 
  }

  public char OrderSource {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSource_get(swigCPtr);
      return ret;
    } 
  }

  public char BuyPositionEffect {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_BuyPositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_BuyPositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char SellPositionEffect {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_SellPositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_SellPositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderBuyPrice {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyPrice_get(swigCPtr);
      return ret;
    } 
  }

  public double OrderSellPrice {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderBuyQty {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyQty_get(swigCPtr);
      return ret;
    } 
  }

  public uint OrderSellQty {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellQty_get(swigCPtr);
      return ret;
    } 
  }

  public char ServerFlag {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ServerFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ServerFlag_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderBuyNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderBuyNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderSellNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderSellNo_get(swigCPtr);
      return ret;
    } 
  }

  public char AddOneIsValid {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_AddOneIsValid_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_AddOneIsValid_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderMarketUserNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderMarketUserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderMarketUserNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderMarketTime {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderMarketTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_OrderMarketTime_get(swigCPtr);
      return ret;
    } 
  }

  public int RefInt {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefInt_set(swigCPtr, value);
    } 
    get {
      int ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefInt_get(swigCPtr);
      return ret;
    } 
  }

  public double RefDouble {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefDouble_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefDouble_get(swigCPtr);
      return ret;
    } 
  }

  public string RefString {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefString_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_RefString_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientBuyOrderNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientBuyOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientBuyOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientSellOrderNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientSellOrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientSellOrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint ErrorCode {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ErrorCode_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ErrorCode_get(swigCPtr);
      return ret;
    } 
  }

  public string ErrorText {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ErrorText_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ErrorText_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientLocalIP {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientLocalIP_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientLocalIP_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientMac {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientMac_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientMac_get(swigCPtr);
      return ret;
    } 
  }

  public string ClientIP {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientIP_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_ClientIP_get(swigCPtr);
      return ret;
    } 
  }

  public string Remark {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_Remark_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIOrderMarketInsertRsp_Remark_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIOrderMarketInsertRsp() : this(TapTradeAPIWrapperPINVOKE.new_TapAPIOrderMarketInsertRsp(), true) {
  }

}

}
