//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapTradeAPI {

public class TapAPIHisMatchQryRsp : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIHisMatchQryRsp(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIHisMatchQryRsp obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIHisMatchQryRsp obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIHisMatchQryRsp() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapTradeAPIWrapperPINVOKE.delete_TapAPIHisMatchQryRsp(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string SettleDate {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_SettleDate_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_SettleDate_get(swigCPtr);
      return ret;
    } 
  }

  public string TradeDate {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_TradeDate_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_TradeDate_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_ExchangeNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_ExchangeNo_get(swigCPtr);
      return ret;
    } 
  }

  public char CommodityType {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CommodityType_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CommodityType_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CommodityNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CommodityNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ContractNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_ContractNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_ContractNo_get(swigCPtr);
      return ret;
    } 
  }

  public string StrikePrice {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_StrikePrice_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_StrikePrice_get(swigCPtr);
      return ret;
    } 
  }

  public char CallOrPutFlag {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CallOrPutFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CallOrPutFlag_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSource {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchSource_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchSource_get(swigCPtr);
      return ret;
    } 
  }

  public char MatchSide {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchSide_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchSide_get(swigCPtr);
      return ret;
    } 
  }

  public char PositionEffect {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_PositionEffect_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_PositionEffect_get(swigCPtr);
      return ret;
    } 
  }

  public char HedgeFlag {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_HedgeFlag_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_HedgeFlag_get(swigCPtr);
      return ret;
    } 
  }

  public double MatchPrice {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchPrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchPrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint MatchQty {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchQty_get(swigCPtr);
      return ret;
    } 
  }

  public string OrderNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_OrderNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_OrderNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint MatchStreamID {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperNo_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchCmbNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchCmbNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchCmbNo_get(swigCPtr);
      return ret;
    } 
  }

  public string ExchangeMatchNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_ExchangeMatchNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_ExchangeMatchNo_get(swigCPtr);
      return ret;
    } 
  }

  public uint MatchUpperStreamID {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchUpperStreamID_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchUpperStreamID_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrencyGroup {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CommodityCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CommodityCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string CommodityCurrency {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CommodityCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CommodityCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public double Turnover {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_Turnover_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_Turnover_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumIncome {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_PremiumIncome_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_PremiumIncome_get(swigCPtr);
      return ret;
    } 
  }

  public double PremiumPay {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_PremiumPay_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_PremiumPay_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountFee {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountFee_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountFee_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountFeeCurrencyGroup {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountFeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountFeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string AccountFeeCurrency {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountFeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountFeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public char IsManualFee {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_IsManualFee_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_IsManualFee_get(swigCPtr);
      return ret;
    } 
  }

  public double AccountOtherFee {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountOtherFee_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_AccountOtherFee_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperFee {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperFee_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperFee_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperFeeCurrencyGroup {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperFeeCurrencyGroup_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperFeeCurrencyGroup_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperFeeCurrency {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperFeeCurrency_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperFeeCurrency_get(swigCPtr);
      return ret;
    } 
  }

  public char IsUpperManualFee {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_IsUpperManualFee_set(swigCPtr, value);
    } 
    get {
      char ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_IsUpperManualFee_get(swigCPtr);
      return ret;
    } 
  }

  public double UpperOtherFee {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperOtherFee_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperOtherFee_get(swigCPtr);
      return ret;
    } 
  }

  public string MatchDateTime {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_MatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public string UpperMatchDateTime {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperMatchDateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_UpperMatchDateTime_get(swigCPtr);
      return ret;
    } 
  }

  public double CloseProfit {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CloseProfit_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CloseProfit_get(swigCPtr);
      return ret;
    } 
  }

  public double ClosePrice {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_ClosePrice_set(swigCPtr, value);
    } 
    get {
      double ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_ClosePrice_get(swigCPtr);
      return ret;
    } 
  }

  public uint CloseQty {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CloseQty_set(swigCPtr, value);
    } 
    get {
      uint ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_CloseQty_get(swigCPtr);
      return ret;
    } 
  }

  public string SettleGroupNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_SettleGroupNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_SettleGroupNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OperatorNo {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_OperatorNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_OperatorNo_get(swigCPtr);
      return ret;
    } 
  }

  public string OperateTime {
    set {
      TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_OperateTime_set(swigCPtr, value);
    } 
    get {
      string ret = TapTradeAPIWrapperPINVOKE.TapAPIHisMatchQryRsp_OperateTime_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIHisMatchQryRsp() : this(TapTradeAPIWrapperPINVOKE.new_TapAPIHisMatchQryRsp(), true) {
  }

}

}
