//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.2.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace TapQuoteAPI {

public class TapAPIQuoteLoginAuth : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal TapAPIQuoteLoginAuth(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(TapAPIQuoteLoginAuth obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(TapAPIQuoteLoginAuth obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~TapAPIQuoteLoginAuth() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          TapQuotePINVOKE.delete_TapAPIQuoteLoginAuth(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string UserNo {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_UserNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_UserNo_get(swigCPtr);
      return ret;
    } 
  }

  public char ISModifyPassword {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_ISModifyPassword_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_ISModifyPassword_get(swigCPtr);
      return ret;
    } 
  }

  public string Password {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_Password_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_Password_get(swigCPtr);
      return ret;
    } 
  }

  public string NewPassword {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_NewPassword_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_NewPassword_get(swigCPtr);
      return ret;
    } 
  }

  public string QuoteTempPassword {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_QuoteTempPassword_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_QuoteTempPassword_get(swigCPtr);
      return ret;
    } 
  }

  public char ISDDA {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_ISDDA_set(swigCPtr, value);
    } 
    get {
      char ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_ISDDA_get(swigCPtr);
      return ret;
    } 
  }

  public string DDASerialNo {
    set {
      TapQuotePINVOKE.TapAPIQuoteLoginAuth_DDASerialNo_set(swigCPtr, value);
    } 
    get {
      string ret = TapQuotePINVOKE.TapAPIQuoteLoginAuth_DDASerialNo_get(swigCPtr);
      return ret;
    } 
  }

  public TapAPIQuoteLoginAuth() : this(TapQuotePINVOKE.new_TapAPIQuoteLoginAuth(), true) {
  }

}

}
